[tox]
envlist =
    mcq
    pdf
    sliding
    trivia
    spell
    world
    whovian
    periodic
skipsdist = True

[testenv]
deps =
    pytest
    flask
    pymupdf

[testenv:mcq]
setenv =
    PYTHONPATH = {toxinidir}/mcq_flashcards:{toxinidir}/trivia_flashcards:{toxinidir}/sliding_rows_flashcards:{toxinidir}/where_in_the_world:{toxinidir}
commands =
    pytest mcq_flashcards test_limit.py test_re_compile.py

[testenv:pdf]
setenv =
    PYTHONPATH = {toxinidir}/pdf_grid_flashcards
commands =
    pytest pdf_grid_flashcards

[testenv:sliding]
setenv =
    PYTHONPATH = {toxinidir}/sliding_rows_flashcards:{toxinidir}
commands =
    pytest sliding_rows_flashcards test_mark_used.py

[testenv:trivia]
setenv =
    PYTHONPATH = {toxinidir}/trivia_flashcards:{toxinidir}
commands =
    pytest trivia_flashcards

[testenv:spell]
setenv =
    PYTHONPATH = {toxinidir}/what_the_spell:{toxinidir}
commands =
    pytest what_the_spell

[testenv:world]
setenv =
    PYTHONPATH = {toxinidir}/where_in_the_world:{toxinidir}
commands =
    pytest where_in_the_world

[testenv:whovian]
setenv =
    PYTHONPATH = {toxinidir}/whovian_degrees:{toxinidir}
commands =
    pytest whovian_degrees

[testenv:price]
setenv =
    PYTHONPATH = {toxinidir}/price_time_machine:{toxinidir}
commands =
    pytest price_time_machine

[testenv:periodic]
setenv =
    PYTHONPATH = {toxinidir}/periodic_name:{toxinidir}
commands =
    pytest periodic_name
